apiVersion: bucket/v1
kind: Schema
metadata:
  name: notifications
spec:
  title: Notifications
  description: Notifications that have been sent by the system.
  acl:
    write: "true==true"
    read: "true==true"
  properties:
    title:
      type: string
    body:
      type: string
    topic:
      type: string
    token:
      type: string
---
apiVersion: function/v1
kind: Function
metadata:
  name: process
spec:
  title: Firebase Push Notification
  description: Function of sending notifications
  code: ./notification/src/notification.js
  runtime:
    name: Node
    language: Javascript
  # environment:
  #   - name: PROJECT_ID
  #     value: ""
  #   - name: PRIVATE_KEY_ID
  #     value: ""
  #   - name: PRIVATE_KEY
  #     value: ""
  #   - name: CLIENT_EMAIL
  #     value: ""
  #   - name: CLIENT_ID
  #     value: ""
  #   - name: AUTH_URI
  #     value: ""
  #   - name: TOKEN_URI
  #     value: ""
  #   - name: AUTH_PROVIDER_X509_CERT_URL
  #     value: ""
  #   - name: CLIENT_X509_CERT_URL
  #     value: ""
  dependency:
    - name: firebase-admin
      version: latest
# ---
# apiVersion: function/v1
# kind: Trigger
# metadata:
#  name: process-sending-notification-when-added
# spec:
#  name: default
#  func: process
#  type: bucket
#  bucketOptions:
#   bucket:
#    resourceFieldRef:
#    bucketName: notifications
#   phase: AFTER
#   type: INSERT