apiVersion: bucket/v1
kind: Schema
metadata:
  name: firebase-notifications
spec:
  title: Notifications
  description: Notifications that have been sent by the system.
  acl:
    write: "true==true"
    read: "true==true"
  properties:
    title:
      type: string
    body:
      type: string
    topic:
      type: string
    token:
      type: string
---
apiVersion: function/v1
kind: Function
metadata:
  name: firebase-push-notification-process
spec:
  title: Firebase Push Notification
  description: Function of sending notifications
  code: ./notification/src/notification.js
  runtime:
    name: Node
    language: Javascript
  environment:
    - name: PROJECT_ID
      value: "Test"
    - name: PRIVATE_KEY_ID
      value: "Test"
    - name: PRIVATE_KEY
      value: "Test"
    - name: CLIENT_EMAIL
      value: "Test"
    - name: CLIENT_ID
      value: "Test"
    - name: AUTH_URI
      value: "Test"
    - name: TOKEN_URI
      value: "Test"
    - name: AUTH_PROVIDER_X509_CERT_URL
      value: "Test"
    - name: CLIENT_X509_CERT_URL
      value: "Test"
    - name: DATABASE_URL
      value: "Test"
  dependency:
    - name: firebase-admin
      version: latest
---
apiVersion: function/v1
kind: Trigger
metadata:
  name: process-sending-notification-when-added
spec:
  name: default
  func: firebase-push-notification-process
  type: bucket
  bucketOptions:
    bucket:
      resourceFieldRef:
        bucketName: firebase-notifications
    phase: AFTER
    type: INSERT